version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  lint:
    executor: node
    steps:
      - install
      - run:
          name: Lint Code
          command: yarn lint
  test:
    executor: node
    steps:
      - install
      - run:
          name: Test Code with Coverage
          command: yarn test --coverage
      - run:
          name: Coveralls
          command: yarn global add coveralls && cat ./coverage/lcov.info | coveralls
  build:
    executor: node
    steps:
      - install
      - run:
          name: Build All Packages
          command: yarn build
      - run:
          name: Build Docs
          command: yarn build-docs

workflows:
  version: 2
  checks:
    jobs:
      - lint
      - test
      - build
